version: "3.8"
services:
  db:
    image: postgres:16.1
    container_name: iceland_weather_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: iceland_weather

  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: iceland_weather_pga
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: strong-password